FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends clang cmake build-essential xvfb wget vim libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev pkg-config libfreetype6-dev freeglut3-dev libasound2-dev libcurl4-openssl-dev libjack-jackd2-dev libxcomposite-dev mesa-common-dev ladspa-sdk webkit2gtk-4.0 libgtk-3-dev && \
    rm -rf /var/lib/apt/lists/*
